version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
    # Disable rebasing because of Netlify build time limit
    rebase-strategy: "disabled"
