name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Extract Node.js version from .nvmrc
      #   id: extract-node-version
      #   run: echo ::set-output name=node_version::$(cat .nvmrc)

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies with Yarn
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
