name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js with Yarn(?)
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the desired Node.js version here

      - name: Install dependencies with Yarn
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: list files in the current directory
        run: ls -a

      - name: Build the project
        run: yarn build

      - name: list files in dist directory
        run: ls -a dist

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e
