name: test_e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract Node.js version from .nvmrc
        id: extract-node-version
        run: echo ::set-output name=node_version::$(cat .nvmrc)
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.extract-node-version.outputs.node_version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: yarn test:e2e
