name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Extract Node.js version from .nvmrc
        id: extract-node-version
        run: echo ::set-output name=node_version::$(cat .nvmrc)

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.extract-node-version.outputs.node_version }}
    
      - name: Install dependencies with Yarn
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: Run Unit tests
        run: yarn test:unit
